platform9/express

ansible.cfg, inventory/openstack_hosts, roles/neutron-prerequisites/defaults/main.yml, roles/pf9-auth/tasks/main.yml, roles/pf9-hostagent/tasks/main.yml, roles/pf9-hostagent/tasks/packages.yml
There are a few bugfixes here. Here's a high-level summary of the changes implemented:
- Remove References to `root` user
- Improve keystone auth
- Update kernel modules to match newer prerequisites
- Fixes when running within a virtualenv
I have tested these changes and successfully ran autodeploy to configure cfe-graham.platform9.net with this branch.
=> Bugfix Merges

INSTALL
Fixed bug found by Matt where 'pip install shade' couldn't remove incompatible versions of PyYAML, python-requests, python-ipaddress installed by gcc (as yum dependencies) because they were installed with yum instead of pip.
=> fixed bug installing python shade package

roles/qemu-kvm-ev/tasks/main.yml
Reverts platform9/autodeploy#26 as it’s currently breaking
=> Revert "add required contentdir yum vars for centos74"

roles/k8s-cluster-attach/tasks/main.yml
Fixed k82-cluster-attach role: HTML body format was invalid for post to Qbert API
=> fixed k82-cluster-attach role

.gitignore, INSTALL, lib/config_util.sh, openstack-cli
Added installer flag to install/configure OpenStack CLI:
[ Installing OpenStack CLI ]
--> Installation Log: /tmp/pf9-INSTALL.log
--> Building pf9-openstack.rc
--> Installing Package Dependenciesgcc openssl-devel python-pip python-wheel python-virtualenv python-virtualenvwrapper
--> Configuring Python Virtual Environment
--> Upgrading PIP
--> Installing OpenStack CLI
(openstack) host list
+--------------------------------------+-------------+----------+
| Host Name                            | Service     | Zone     |
+--------------------------------------+-------------+----------+
| dwpf9-kvm-01.platform9.net.novalocal | conductor   | internal |
| dwpf9-kvm-01.platform9.net.novalocal | network     | internal |
| dwpf9-kvm-01.platform9.net.novalocal | consoleauth | internal |
| …
=> added '-o|--oscli' flag to INSTALL (install/configure OpenStack CLI)

pf9-autodeploy.yml, roles/network-hook/tasks/main.yml, roles/neutron-prerequisites/tasks/main.yml, roles/post-hook/tasks/main.yml, roles/pre-hook/tasks/main.yml
Added 3 hooks to Auto-Deploy:
* pre_hook
* network_hook
* post_hook
Each hook is a stub playbook that exists in the roles/ directory that a customer can modify as needed to extend Auto-Deploy.  For example, if a customer wanted to change the way networking is configured, they can add their own code to roles/network-hook/tasks/main.yml, or if they want to run a role before/after auto-deploy they can modify roles/pre-hook and roles/post-hook, respectively.
=> added pre_hook, post_hook, and network_hook (user-defined roles)

group_vars/cinder.yml, group_vars/hypervisors.yml, pf9-autodeploy.yml, roles/pre-flight-checks/tasks/main.yml
Added pre-flight-checks role with one check:
* validates that there is enough free space in the filesystem hosting the Cinder image conversion directory. 
NOTE 1: runs on Cinder nodes only.
NOTE 2: the minimal value is defined in group_vars/cinder.yml but can be overridden via "INSTALL -e <extra-vars>"
=> added pre-flight-checks role (with one check)

roles/network-hook/tasks/main.yml
Fixes issue #96, which was introduced in pull request #36. This fix is critical given any customer deployment without this today will likely be broken.
=> Modifying logic to apply when br-pf9 exists

lib/hosts.tpl, lib/setupd.rpm, roles/common/tasks/main.yml
Added 2 new inventory variables (to lib/hosts.tpl): 
* pf9_uid=1001
* pf9_gid=1001
And updated the roles/common to use these values when adding the 'pf9' user and the 'pf9group' group. 
NOTE: previously, the user/group was created by the pf9-hostagent installer.
=> added feature to control uid/gid for pf9 service account

group_vars/hypervisors.yml
live_migration was defined as a String in group_vars/hypervisors.yaml, but the when clause in pf9-express.yaml tested for a Boolean value.  So redefined live_migration to be a Boolean value.
=> Hot Patch:  fixed execution of live-migration role

roles/qemu-kvm-ev/tasks/main.yml
Added RHEL support to qemu-kvm-ev role to install correct Qemu packages based on OS (Centos v RHEL)
Validate on two RHEL 7.4 hypervisors
=> updated qemu-kvm-ev role to work on RHEL

Dockerfile
Modified the entrypoint command to allow direct running of pf9-express by simply passing options and arguments to docker run.
Modified ssh_config to turn off strict host key checking for the container to enable ansible usage.
=> update entrypoint, and modify ssh_config to allow ansible functionality

Dockerfile
A simple Dockerfile that encapsulates the pf9-express functionality. I haven't done any testing except running it. I will also push this to Dockerhub once I do some testing.
=> Adding a simple dockerfile for the pf9-express

pf9-express.yml
we missed updating the host group in pf9-express.yml so bonding gets skipped currently
=> replace bond-config with bond_config to meet ansible dictates

lib/hosts.tpl
This patch replaces a hyphen with an underscore (from bond-config to bond_config) in the respective group name.
=> Replace hyphen with underscore for bond_config group

group_vars/glance.yml
This patch fixes an issue resulting from the upstream image URLs being changed and the image(s) not being downloaded. Ansible is not following the 302s from the server. There is an undocumented 'follow' argument for get_url that might be of interest later.
=> Image URLs have been updated (302 not followed)

pf9-express
This is mostly a copy of @jb4free's work on https://github.com/platform9/express/pull/233 but removes some unneeded changes and incorporates the feedback I provided on #233. We are merging this branch as it's been more recently tested.
Addresses issue #188 
I've tested several combinations
- PMO & PMK hosts in primary region
- PMO & PMK hosts in secondary region
- PMO hosts that are Ubuntu
- PMO hosts that are CentOS
- PMK hosts that are Ubuntu
- CentOS 7.6, Ubuntu 16.04, & Ubuntu 18.04 Express control host
=> Multi region support fix

ansible.cfg
This will improve the output of the report and is more useful overall versus individual tasks. Individual tasks is useful in debugging if you are attempting to optimize a given role.
Example output:
```
Wednesday 28 August 2019  22:01:44 +0000 (0:00:00.148)       0:07:13.621 ****** 
=============================================================================== 
wait-for-convergence -------------------------------------------------- 356.82s
pf9-hostagent ---------------------------------------------------------- 30.73s
common ----------------------------------------------------------------- 13.08s
map-role --------------------------------------------------------------- 10.39s
gather_facts ------------------------------------------------------------ 7.71s
pf9-auth …
```
=> Update Ansible config to profile roles versus tasks

pf9-express, pf9-k8s-express.yml
This change breaks out the PMK specific steps into its own playbook. Note that the original pf9-express.yml playbook remains unchanged. This skips over all the non PMK tasks that are part of the main playbook. The new playbook has been completely inspired by the original playbook (mainly removed all the unnecessary roles/tasks)
Also, a new command option `--pmk` is added to the pf9-express bash script to allow invoking this new ansible playbook. Another tweak to this command is that it will fail immediately when the ansible step fails to return a non-zero exit code (unlike the behavior of other commands)
=> Add a new ansible playbook for PMK only

roles/common/tasks/main.yml, roles/pf9-hostagent/tasks/certless-hostinstaller-setup.yml, roles/pf9-hostagent/tasks/main.yml
Using failed as a jinja2 filter is deprecated as Ansible 2.5 (current latest
version is 2.9). It is noticed that using it as a filter is leading to failures
on certain setups. Move to using the new way of using failed as a test instead.
See more details here:
https://docs.ansible.com/ansible/devel/porting_guides/porting_guide_2.5.html?highlight=failed#deprecated
Also, some minor cleanup/fixes.
=> Move failed jinja2 filter to a test

pf9-express
It would be convenient if users can optionally specify the log location of all
the Ansible tasks. The default continues to be the same previous behavior.
Tested running this on my local setup.
=> Allow users to pass a log file location

roles/common/tasks/redhat.yml
changed pipe for is
Ran against rhel host and successfully onboarded.
=> Move RedHat jinja2 filter to a test for Ansible 2.9+ compatibility

pf9-express
pf9-express was failing for the machines running on python2 while obtaining the keystone token with the error - `openstacksdk is required for this module`.
Changed the pf9-express to install `openstacksdk 0.39.0` in prereqs as OpenStacksdk has dropped support for pip2. 
-  Edited pf9-express code to replace shade with 'openstacksdk==0.39.0' . 
one will have to uninstall all the existing openstacksdk versions using  - pip uninstall openstacksdk . This should be run multiple times to remove all the existing versions. 
pf9-express should be run without bypassing the pre-reqs to pick the new changes.
=> Changed to install openstacksdk==0.39.0 in prereqs for python2 support

roles/neutron-prerequisites/tasks/redhat.yml, roles/neutron-prerequisites/tasks/ubuntu.yml
**Summary** 
This change will ensure that ovs-version 2.11 is being installed on Ubuntu and Centos hosts as per the prerequisites for PMO 4.5 
I have tested this on  Ubuntu and Centos hosts.
=> updated neutron prereqs role with the right repo so ovs version 2.11 will be pulled

roles/pf9-auth/tasks/main.yml
Starting with the Platform9 5.0 release, the v2.0 Keystone endpoint will be removed. This change should still be compatible with Platform9 environments < 5.0 as well.
=> Change Keystone endpoint from v2.0 -> v3

roles/map-role/tasks/main.yml, roles/map-role/templates/pf9-cindervolume-lvm.j2
The iscsi_ip_address option in Cinder was updated to target_ip_address.
https://docs.openstack.org/cinder/train/configuration/block-storage/samples/cinder.conf.html 
This change was tested in the SE lab.
=> Update cinder config template

pf9-k8s-upgrade.yml, roles/map-role/tasks/main.yml, roles/wait-for-convergence/tasks/main.yml
1. Update k8s upgrade playbook to expect proxy environment and pf9-kube role version
2. Updated map-role to expect pf9-kube role version as the nodes in a
cluster need to converge to a specific version of pf9-kube
=> Add changes to cluster upgrade playbook to work with multi-version and proxy

roles/pre-flight-checks-openstack/tasks/main.yml
Fixes following error when groups `[cinder]` is not used in inventory file
```
TASK [pre-flight-checks-openstack : check if {{cinder_image_conversion_cache}} directory exists] ****************************************
Friday 28 July 2023  10:47:55 +0000 (0:00:00.043)       0:00:15.304 ***********
fatal: [sn-u3]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'cinder_image_conversion_cache' is undefined\n\nThe error appears to be in '/root/express.latest/roles/pre-flight-checks-openstack/tasks/main.yml': line 100, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"check if {{cinder_image_conversion_cache}} directory exists\"\n  ^ here\nWe could be wrong, but this …
```
=> added host group guard to cinder pre-flight checks

roles/pre-flight-checks-openstack/tasks/main.yml
If an inventory has only [hypervisors] group defined and does NOT have [cinder] group, existing `when` condition in a 'cinder' related tasks is failing to execute because the current host(`inventory_hostname`) is not found in the `cinder` group. This patch is modifying that `when` condition to first check if the [cinder] group exist in the inventory and then check if the current host is part of it.
=> Update in 'pre-flight-checks-openstack', main.yml

ansible.cfg
Sometimes the task execution fails with below error because the default timeout value for connection plugin is 10s.
`FAILED! => { "msg": "Timeout (12s) waiting for privilege escalation prompt: " }`
This patch is to increase the `timeout` value to 60s in the working directory's `ansible.cfg` that solves the issue.
=> Update ansible.cfg with `timeout` parameter.

roles/neutron-prerequisites/tasks/main.yml, roles/neutron-prerequisites/tasks/rocky9.yml, roles/secure-live-migration/handlers/main.yaml, roles/secure-live-migration/tasks/configure.yaml, roles/secure-live-migration/tasks/main.yaml
[1] Removes the play for disabling NetworkManager in Rocky9. Rocky9 with NM enabled hypervisor will be supported with this PR merged.
- Tested with NetworkManager enabled, keyfiles to manage Network interfaces. Removed init script plugin from NM.
[2] Enhanced Secure Live migration role:
- Libvirtd systemd service is restarted with TLS socket in U22.04, 20.04, Rocky and RHEL 8 and 9.
Attaching log from rocky9 host.
[pf9-express.2024-10-17_02:04:49.log](https://github.com/user-attachments/files/17415564/pf9-express.2024-10-17_02.04.49.log)
=> Private/snimje/cs 1675 - NM support in Rocky9, Libvirtd restart in Rocky9, 8, Ubuntu 20.04, 22.04 handler update
